### ISSUE TITLE
Doesn't merge hashes

### ISSUE THREAD

**Issue by ae-dg** [cstgrid/k8comp#1]
If `common.yaml` contains

```
---
global:
  AGAIN: 2
```

and another yaml file contains

```
---
global:
  TEST: 1
```
when using `%{global}` in  a yaml file in projects the output only contains TEST instead of both TEST and AGAIN.

This can be checked by running `hiera` by hand.  Adding the `-h` parameter to the running of `hiera` seems to merge the two `global` hashes together.

**Comment by catalinpan** [comment]
I've checked that and you're right. Currently it doesn't merge the values, however if the -h is added hiera expects to have only hashes which will break the functionality for string variables.

```
---
global: test100
```
error
```
/var/lib/gems/2.3.0/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml_backend.rb:60:in `block in lookup': Hiera type mismatch: expected Hash and got String (Exception)
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera/backend.rb:95:in `block in datasources'
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera/backend.rb:90:in `map'
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera/backend.rb:90:in `datasources'
        from /var/lib/gems/2.3.0/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml_backend.rb:29:in `lookup'
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera/backend.rb:18:in `lookup'
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera/backend.rb:274:in `block (2 levels) in lookup'
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera/backend.rb:272:in `catch'
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera/backend.rb:272:in `block in lookup'
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera/backend.rb:267:in `each'

        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera/backend.rb:267:in `lookup'
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/lib/hiera.rb:117:in `lookup'
        from /var/lib/gems/2.3.0/gems/hiera-3.4.2/bin/hiera:246:in `<top (required)>'
        from /usr/local/bin/hiera:23:in `load'
        from /usr/local/bin/hiera:23:in `<main>'
```
Would be nice to have the functionality requested. I will check what can be done but feel free to create a PR if you would like to resolve this.

**Comment by catalinpan** [comment]
I have pushed a change in development. When you have the chance can you please check if this fixes the issue?
#2

**Comment by ae-dg** [comment]
Preliminary testing looks good. 👍

**Comment by catalinpan** [comment]
I believe this is now resolved. Please reopen the issue if the fix doesn't work as expected.
